use Rex -feature => ['1.0'];

user "root";
password "box";

group servers => "localhost";

task "setup", group => "servers", sub {
  pkg "ntp",
    ensure => "present";

  file "/etc/ntp.conf",
    source => "files/etc/ntp.conf",
    owner  => "root",
    group  => "root",
    mode   => 644;

  service "ntp",
    ensure => "started";
};
